# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_in_menu',
            field=models.BooleanField(default=b'', verbose_name=b'Published in main menu'),
        ),
    ]
