# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
    ]
