# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170105_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_in_second',
            field=models.BooleanField(default=b'', verbose_name=b'Published in second menu'),
        ),
    ]
