# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170124_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='slug',
        ),
        migrations.AddField(
            model_name='overview',
            name='icon',
            field=models.CharField(blank=True, max_length=250, verbose_name='Icon'),
        ),
    ]
