# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 12:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170124_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Text')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Pic')),
                ('published', models.BooleanField(verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('category', models.ManyToManyField(blank=True, related_name='accessories', related_query_name='access', to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'verbose_name': 'Accessory',
                'ordering': ['ordering'],
                'db_table': 'accessories',
            },
        ),
    ]
