# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_prod_page',
            field=models.BooleanField(default='', verbose_name='Published on product page'),
        ),
    ]
