# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_published_prod_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_prod_page',
        ),
        migrations.AddField(
            model_name='product',
            name='published_fl_page',
            field=models.BooleanField(default='', verbose_name='Published on fluid page'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_sm_page',
            field=models.BooleanField(default='', verbose_name='Published on smokemachine page'),
        ),
    ]
