# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170125_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_fl_page',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_sm_page',
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.BooleanField(default='', verbose_name='Published on product page'),
        ),
    ]
