# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170125_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Related Category'),
        ),
    ]
