# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 00:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_related_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='text',
        ),
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='slogan',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Slogan'),
        ),
    ]
