# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20170126_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideproduct',
            options={'ordering': ['ordering'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='slideproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Изображение'),
        ),
    ]
