# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20170131_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slideproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
    ]
