# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 02:57
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20170131_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproduct',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='support',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=product.models.make_upload_path, verbose_name='Image'),
        ),
    ]
