# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20170131_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideproduct',
            name='published',
        ),
        migrations.AddField(
            model_name='slideproduct',
            name='published_bg',
            field=models.BooleanField(default=0, verbose_name='Published as BG'),
        ),
    ]
