# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20170131_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideproduct',
            name='published_portf',
            field=models.BooleanField(default=0, verbose_name='Published in Portfolio'),
        ),
    ]
