# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_slideproduct_published_portf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideproduct',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slideproduct', to='product.Category', verbose_name='Category'),
        ),
    ]
