# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20170210_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_published_in_all',
            field=models.BooleanField(default='', verbose_name='Do not Published on All products'),
        ),
        migrations.AddField(
            model_name='slideproduct',
            name='published_in_all',
            field=models.BooleanField(default=0, verbose_name='Published in All Products'),
        ),
    ]
