# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_product_related_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitemproduct',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='menuitem', related_query_name='menuit', to='product.Category', verbose_name='Category'),
        ),
    ]
