# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-07 15:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snipet',
        ),
        migrations.DeleteModel(
            name='Top',
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name': 'Meta description', 'verbose_name_plural': 'Meta descriptions'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Menu', verbose_name=b'Name menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Ordering'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.MenuItem', verbose_name=b'Parent menu item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='published',
            field=models.BooleanField(verbose_name=b'Published'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'URL'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='favicon_slug',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'URL favicon'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_author',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'Meta Author'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=b'Meta description'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'Meta keywords'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'Meta Title'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='published',
            field=models.BooleanField(default=0, verbose_name=b'Published'),
        ),
    ]
