# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='published_all_prod',
            field=models.BooleanField(default='', verbose_name='Published on Products page'),
        ),
    ]
