# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_slide_published_all_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='published_portfolio',
            field=models.BooleanField(default='', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='published_all_prod',
            field=models.BooleanField(default='', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='published_main',
            field=models.BooleanField(default='', verbose_name='Carousel'),
        ),
    ]
