# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 00:45
from __future__ import unicode_literals

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170113_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=content.models.make_upload_path, verbose_name='favicon.ico'),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to=content.models.make_upload_path, verbose_name='Image'),
        ),
    ]
