# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 02:57
from __future__ import unicode_literals

import content.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170131_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=content.models.make_upload_path, verbose_name='Image'),
        ),
    ]
