# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170131_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='isHorizont',
            field=models.BooleanField(default='', verbose_name='isHorizont'),
        ),
    ]
